package lexgen

import (
	"fmt"
	"io"
	"log/slog"
	"slices"
	"strings"

	"github.com/bluesky-social/indigo/atproto/lexicon"
	"github.com/bluesky-social/indigo/atproto/syntax"
)

// GenConfig configures the code generator output. The zero value is not valid;
// use NewGenConfig, GlexConfig, or LegacyConfig.
type GenConfig struct {
	RegisterLexiconTypeID bool
	// one of: "type-decoder", "map-string-any", "json-raw-message"
	UnknownType string
	WarningText string
	LegacyMode  bool

	// --- go-dasl / glex extensions: ---

	// RuntimeImport is the full Go import path of the glex runtime package
	// (e.g. "github.com/streamplace/glex/runtime"). Required when DaslMode is
	// true; the import alias is RuntimeAlias (default "glexrt").
	RuntimeImport string
	// RuntimeAlias is the import alias used for RuntimeImport in generated code.
	// Defaults to "glexrt".
	RuntimeAlias string

	// PkgNameOverrides maps a computed nsidPkgName to a forced Go package name.
	// Applied for both the emitted `package` clause and same-package reference
	// detection.
	PkgNameOverrides map[string]string

	// ExtraImports maps a computed nsidPkgName (the reference's package alias)
	// to a full Go import spec, for references to first-party packages that
	// live outside the generated set.
	ExtraImports map[string]string

	// ExternalTypeMappings maps an NSID authority prefix (e.g. "com.atproto.")
	// to a full Go import spec (e.g.
	// `comatproto "github.com/bluesky-social/indigo/api/atproto"`). When nil,
	// external refs that don't resolve via PkgNameOverrides or ExtraImports
	// produce an error.
	ExternalTypeMappings map[string]string

	// DaslMode switches serialization to go-dasl (DRISL): blob/link/bytes
	// fields use the runtime value types, and every generated struct gets
	// thin cbg.CBORMarshalor-shaped adapter methods delegating to go-dasl.
	DaslMode bool
}

// runtimeAlias returns the configured runtime import alias, defaulting to
// "glexrt".
func (c *GenConfig) runtimeAlias() string {
	if c.RuntimeAlias != "" {
		return c.RuntimeAlias
	}
	return "glexrt"
}

// runtimeImportSpec returns the full import spec for the runtime package,
// e.g. `glexrt "github.com/streamplace/glex/runtime"`. Returns empty string
// if RuntimeImport is unset.
func (c *GenConfig) runtimeImportSpec() string {
	if c.RuntimeImport == "" {
		return ""
	}
	return fmt.Sprintf(`%s "%s"`, c.runtimeAlias(), c.RuntimeImport)
}

// GlexConfig is the clean go-dasl codegen profile. Generated structs use the
// glex runtime value types and serialize as canonical DAG-CBOR via go-dasl.
// No indigo lexutil dependency, no cborgen tags (go-dasl reads json: tags).
func GlexConfig(runtimeImport string) *GenConfig {
	return &GenConfig{
		RegisterLexiconTypeID: true,
		UnknownType:           "type-decoder",
		WarningText:           "Code generated by glex; DO NOT EDIT.",
		DaslMode:              true,
		RuntimeImport:         runtimeImport,
	}
}

// NewGenConfig returns a minimal config (map[string]any for unknowns, no
// registration, no DaslMode). Mostly useful as a starting point for custom
// configs.
func NewGenConfig() *GenConfig {
	return &GenConfig{
		UnknownType: "map-string-any",
		WarningText: "Code generated by glex; DO NOT EDIT.",
	}
}

// LegacyConfig returns the legacy (cmd/lexgen-compatible) codegen profile. This
// emits cborgen tags, RegisterType inits into indigo's lexutil, and
// LexiconTypeDecoder view fields — for consumers that still use indigo's
// lexutil runtime. DaslMode is off.
func LegacyConfig() *GenConfig {
	return &GenConfig{
		RegisterLexiconTypeID: true,
		UnknownType:           "type-decoder",
		WarningText:           "Code generated by glex (legacy mode); DO NOT EDIT.",
		LegacyMode:            true,
	}
}

// Core implementation of Go code generation for a single Lexicon schema file
// (multiple definitions), building on a pre-parsed FlatLexicon.
type CodeGenerator struct {
	Config *GenConfig
	Lex    *FlatLexicon
	Cat    lexicon.Catalog
	Out    io.Writer
}

// WriteLexicon outputs Go source code to the Out io.Writer.
func (gen *CodeGenerator) WriteLexicon() error {

	if gen.Config.WarningText != "" {
		fmt.Fprintf(gen.Out, "// %s\n\n", gen.Config.WarningText)
	}
	fmt.Fprintf(gen.Out, "// Lexicon schema: %s\n\n", gen.Lex.NSID)
	fmt.Fprintf(gen.Out, "package %s\n\n", gen.PkgName())
	fmt.Fprintln(gen.Out, "import (")
	for dep := range gen.deps() {
		fmt.Fprintf(gen.Out, "\t%s\n", dep)
	}
	fmt.Fprint(gen.Out, ")\n\n")

	for _, ft := range gen.Lex.Types {
		slog.Debug("generating type", "nsid", gen.Lex.NSID, "def", ft.DefName, "path", ft.Path, "type", ft.Type)
		if err := gen.WriteType(&ft); err != nil {
			return err
		}
	}
	return nil
}

// pkgNameFor computes the Go package name for an NSID, applying any configured
// overrides.
func (gen *CodeGenerator) pkgNameFor(nsid syntax.NSID) string {
	n := nsidPkgName(nsid)
	if override, ok := gen.Config.PkgNameOverrides[n]; ok {
		return override
	}
	return n
}

func (gen *CodeGenerator) PkgName() string {
	n := gen.pkgNameFor(gen.Lex.NSID)
	if gen.Config.LegacyMode {
		switch n {
		case "appbsky":
			return "bsky"
		case "comatproto":
			return "atproto"
		case "toolsozone":
			return "ozone"
		case "chatbsky":
			return "chat"
		}
	}
	return n
}

func (gen *CodeGenerator) baseName() string {
	return nsidBaseName(gen.Lex.NSID)
}

func (gen *CodeGenerator) FileName() string {
	return nsidFileName(gen.Lex.NSID) + ".go"
}

// rtAlias returns the runtime import alias to use in emitted code, or
// "lexutil" in legacy (non-DaslMode) mode.
func (gen *CodeGenerator) rtAlias() string {
	if gen.Config.DaslMode {
		return gen.Config.runtimeAlias()
	}
	return "lexutil"
}

func (gen *CodeGenerator) deps() map[string]bool {
	d := map[string]bool{
		"\"context\"":       true,
		"\"fmt\"":           true,
		"\"io\"":            true,
		"\"bytes\"":         true,
		"\"encoding/json\"": true,
	}
	// In legacy mode, import indigo's lexutil. In DaslMode, import the glex
	// runtime instead.
	if gen.Config.DaslMode {
		if spec := gen.Config.runtimeImportSpec(); spec != "" {
			d[spec] = true
		}
		d["cbg \"github.com/whyrusleeping/cbor-gen\""] = true
	} else {
		d["lexutil \"github.com/bluesky-social/indigo/lex/util\""] = true
		d["cbg \"github.com/whyrusleeping/cbor-gen\""] = true
	}

	for ext := range gen.Lex.ExternalRefs {
		// Check configurable external type mappings first.
		mapped := false
		for prefix, imp := range gen.Config.ExternalTypeMappings {
			if strings.HasPrefix(ext, prefix) {
				d[imp] = true
				mapped = true
				break
			}
		}
		if mapped {
			continue
		}
		if gen.pkgNameForRef(ext) == gen.PkgName() {
			// same-package reference; no import needed.
		} else if imp, ok := gen.Config.ExtraImports[gen.rawPkgNameForRef(ext)]; ok {
			d[imp] = true
		} else {
			slog.Error("unhandled external reference", "ref", ext)
		}
	}
	return d
}

func (gen *CodeGenerator) pkgNameForRef(ref string) string {
	nsidStr := strings.SplitN(ref, "#", 2)[0]
	nsid, err := syntax.ParseNSID(nsidStr)
	if err != nil {
		return ""
	}
	return gen.pkgNameFor(nsid)
}

func (gen *CodeGenerator) rawPkgNameForRef(ref string) string {
	nsidStr := strings.SplitN(ref, "#", 2)[0]
	nsid, err := syntax.ParseNSID(nsidStr)
	if err != nil {
		return ""
	}
	return nsidPkgName(nsid)
}

func (gen *CodeGenerator) WriteType(ft *FlatType) error {

	switch v := ft.Schema.Inner.(type) {
	case lexicon.SchemaRecord:
		if gen.Config.RegisterLexiconTypeID {
			fmt.Fprintf(gen.Out, "func init() {\n")
			fmt.Fprintf(gen.Out, "\t%s.RegisterType(\"%s\", &%s{})\n", gen.rtAlias(), gen.Lex.NSID, gen.baseName())
			fmt.Fprintf(gen.Out, "}\n\n")
		}
		// HACK: insert record-level description into object if nil
		if v.Description != nil && v.Record.Description == nil {
			v.Record.Description = v.Description
		}
		if err := gen.writeStruct(ft, &v.Record); err != nil {
			return err
		}
	case lexicon.SchemaQuery:
		return gen.writeEndpoint(ft, defDescription(ft.Schema), v.Parameters, v.Output, nil, false)
	case lexicon.SchemaProcedure:
		return gen.writeEndpoint(ft, defDescription(ft.Schema), v.Parameters, v.Output, v.Input, true)
	case lexicon.SchemaSubscription:
		// pass; we only generate message types, not overall subscription
	case lexicon.SchemaPermissionSet, lexicon.SchemaPermission:
		// pass for Go codegen
	case lexicon.SchemaToken:
		// TODO: pass for now; could be a var/const?
	case lexicon.SchemaString, lexicon.SchemaInteger, lexicon.SchemaBoolean, lexicon.SchemaUnknown:
		// skip
	case lexicon.SchemaObject:
		if gen.Config.RegisterLexiconTypeID && ft.DefName == "main" && len(ft.Path) == 0 {
			fmt.Fprintf(gen.Out, "func init() {\n")
			fmt.Fprintf(gen.Out, "\t%s.RegisterType(\"%s#main\", &%s{})\n", gen.rtAlias(), gen.Lex.NSID, gen.baseName())
			fmt.Fprintf(gen.Out, "}\n\n")
		}
		if err := gen.writeStruct(ft, &v); err != nil {
			return err
		}
	case lexicon.SchemaUnion:
		return gen.writeUnion(ft, &v)
	case lexicon.SchemaRef:
		// skip for now. could be an alias type?
	default:
		return fmt.Errorf("unhandled schema type for codegen: %T", ft.Schema.Inner)
	}

	return nil
}

func isRequired(required []string, fname string) bool {
	return slices.Contains(required, fname)
}
