package lexgen

import (
	"fmt"
	"io"
	"log/slog"
	"slices"
	"strings"

	"github.com/bluesky-social/indigo/atproto/lexicon"
	"github.com/bluesky-social/indigo/atproto/syntax"
)

// GenConfig configures the code generator output.
type GenConfig struct {
	// ModulePath is the Go module path that generated packages will be
	// imported under (e.g. "stream.place/streamplace/gen"). Cross-package
	// references are computed as ModulePath/nsidPkgName(ref).
	ModulePath string

	WarningText string
}

// NewGenConfig returns the default config.
func NewGenConfig(modulePath string) *GenConfig {
	return &GenConfig{
		ModulePath:  modulePath,
		WarningText: "Code generated by glex; DO NOT EDIT.",
	}
}

// Core implementation of Go code generation for a single Lexicon schema file
// (multiple definitions), building on a pre-parsed FlatLexicon.
type CodeGenerator struct {
	Config *GenConfig
	Lex    *FlatLexicon
	Cat    lexicon.Catalog
	Out    io.Writer
}

// WriteLexicon outputs Go source code to the Out io.Writer.
func (gen *CodeGenerator) WriteLexicon() error {

	if gen.Config.WarningText != "" {
		fmt.Fprintf(gen.Out, "// %s\n\n", gen.Config.WarningText)
	}
	fmt.Fprintf(gen.Out, "// Lexicon schema: %s\n\n", gen.Lex.NSID)
	fmt.Fprintf(gen.Out, "package %s\n\n", gen.PkgName())
	fmt.Fprintln(gen.Out, "import (")
	for dep := range gen.deps() {
		fmt.Fprintf(gen.Out, "\t%s\n", dep)
	}
	fmt.Fprint(gen.Out, ")\n\n")

	for _, ft := range gen.Lex.Types {
		slog.Debug("generating type", "nsid", gen.Lex.NSID, "def", ft.DefName, "path", ft.Path, "type", ft.Type)
		if err := gen.WriteType(&ft); err != nil {
			return err
		}
	}
	return nil
}

// pkgNameFor computes the Go package name for an NSID.
func (gen *CodeGenerator) pkgNameFor(nsid syntax.NSID) string {
	return nsidPkgName(nsid)
}

func (gen *CodeGenerator) PkgName() string {
	return gen.pkgNameFor(gen.Lex.NSID)
}

func (gen *CodeGenerator) baseName() string {
	return nsidBaseName(gen.Lex.NSID)
}

func (gen *CodeGenerator) FileName() string {
	return nsidFileName(gen.Lex.NSID) + ".go"
}

// rtAlias returns the runtime import alias used in generated code.
func (gen *CodeGenerator) rtAlias() string {
	return "glex"
}

// regAlias returns the alias for the type registry. Same as rtAlias since
// we always use the glex runtime.
func (gen *CodeGenerator) regAlias() string {
	return "glex"
}

func (gen *CodeGenerator) deps() map[string]bool {
	d := map[string]bool{
		"\"context\"":                        true,
		"\"fmt\"":                            true,
		"\"io\"":                             true,
		"\"bytes\"":                          true,
		"\"encoding/json\"":                  true,
		"glex \"github.com/streamplace/glex/runtime\"": true,
		"cbg \"github.com/whyrusleeping/cbor-gen\"":     true,
	}

	for ext := range gen.Lex.ExternalRefs {
		if gen.pkgNameForRef(ext) == gen.PkgName() {
			// same-package reference; no import needed.
			continue
		}
		// Cross-package reference: compute the import path from ModulePath.
		if gen.Config.ModulePath != "" {
			pkg := gen.rawPkgNameForRef(ext)
			imp := fmt.Sprintf(`%s "%s/%s"`, pkg, gen.Config.ModulePath, pkg)
			d[imp] = true
		} else {
			slog.Error("unhandled external reference (no ModulePath configured)", "ref", ext)
		}
	}
	return d
}

func (gen *CodeGenerator) pkgNameForRef(ref string) string {
	nsidStr := strings.SplitN(ref, "#", 2)[0]
	nsid, err := syntax.ParseNSID(nsidStr)
	if err != nil {
		return ""
	}
	return gen.pkgNameFor(nsid)
}

func (gen *CodeGenerator) rawPkgNameForRef(ref string) string {
	nsidStr := strings.SplitN(ref, "#", 2)[0]
	nsid, err := syntax.ParseNSID(nsidStr)
	if err != nil {
		return ""
	}
	return nsidPkgName(nsid)
}

func (gen *CodeGenerator) WriteType(ft *FlatType) error {

	switch v := ft.Schema.Inner.(type) {
	case lexicon.SchemaRecord:
		fmt.Fprintf(gen.Out, "func init() {\n")
		fmt.Fprintf(gen.Out, "\t%s.RegisterType(\"%s\", &%s{})\n", gen.regAlias(), gen.Lex.NSID, gen.baseName())
		fmt.Fprintf(gen.Out, "}\n\n")
		// HACK: insert record-level description into object if nil
		if v.Description != nil && v.Record.Description == nil {
			v.Record.Description = v.Description
		}
		if err := gen.writeStruct(ft, &v.Record); err != nil {
			return err
		}
	case lexicon.SchemaQuery:
		return gen.writeEndpoint(ft, defDescription(ft.Schema), v.Parameters, v.Output, nil, false)
	case lexicon.SchemaProcedure:
		return gen.writeEndpoint(ft, defDescription(ft.Schema), v.Parameters, v.Output, v.Input, true)
	case lexicon.SchemaSubscription:
		// pass; we only generate message types, not overall subscription
	case lexicon.SchemaPermissionSet, lexicon.SchemaPermission:
		// pass for Go codegen
	case lexicon.SchemaToken:
		// TODO: pass for now; could be a var/const?
	case lexicon.SchemaString, lexicon.SchemaInteger, lexicon.SchemaBoolean, lexicon.SchemaUnknown:
		// skip
	case lexicon.SchemaObject:
		if ft.DefName == "main" && len(ft.Path) == 0 {
			fmt.Fprintf(gen.Out, "func init() {\n")
			fmt.Fprintf(gen.Out, "\t%s.RegisterType(\"%s#main\", &%s{})\n", gen.regAlias(), gen.Lex.NSID, gen.baseName())
			fmt.Fprintf(gen.Out, "}\n\n")
		}
		if err := gen.writeStruct(ft, &v); err != nil {
			return err
		}
	case lexicon.SchemaUnion:
		return gen.writeUnion(ft, &v)
	case lexicon.SchemaRef:
		// skip for now. could be an alias type?
	default:
		return fmt.Errorf("unhandled schema type for codegen: %T", ft.Schema.Inner)
	}

	return nil
}

func isRequired(required []string, fname string) bool {
	return slices.Contains(required, fname)
}
