// Code generated by glex; DO NOT EDIT.

// Lexicon schema: com.example.embed

package comexample

import (
	"encoding/json"
	"fmt"
	"io"

	glex "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

func init() {
	glex.RegisterType("com.example.embed", &Embed{})
}

// A test record with union fields.
type Embed struct {
	LexiconTypeID string `json:"$type,omitempty"`
	// createdAt: Creation timestamp.
	CreatedAt string `json:"createdAt"`
	// extras: Additional media items.
	Extras []Embed_Extras_Elem `json:"extras,omitempty"`
	// fallback: Optional fallback media.
	Fallback *Embed_Fallback `json:"fallback,omitempty"`
	// media: The primary embedded media.
	Media Embed_Media `json:"media"`
}

// RecordTypeID implements glex.Record.
func (t *Embed) RecordTypeID() string { return "com.example.embed" }

// MarshalJSON stamps the $type field, like MarshalCBOR does. The value
// receiver operates on a copy, so the record is never mutated and both
// Embed and *Embed marshal with $type.
func (t Embed) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "com.example.embed"
	type alias Embed
	return json.Marshal((alias)(t))
}

func (t *Embed) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	// stamp $type on a copy so marshal never mutates the record
	cp := *t
	cp.LexiconTypeID = "com.example.embed"
	return glex.MarshalCBOR(w, &cp)
}

func (t *Embed) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

type Embed_Extras_Elem struct {
	Embed_External *Embed_External
	Embed_Images   *Embed_Images
	// Raw preserves a variant whose $type is not in this union's generated
	// set, so unrecognized variants still round-trip losslessly through
	// decode/re-encode. Nil when a known variant is set.
	Raw *glex.RawRecord
}

// MarshalJSON emits the set variant, stamped with its $type, per the atproto
// union wire format. The value receiver stamps a copy, so the variant is
// never mutated and both Embed_Extras_Elem and *Embed_Extras_Elem marshal correctly.
func (t Embed_Extras_Elem) MarshalJSON() ([]byte, error) {
	if t.Embed_External != nil {
		cp := *t.Embed_External
		cp.LexiconTypeID = "com.example.embed#external"
		return json.Marshal(&cp)
	}
	if t.Embed_Images != nil {
		cp := *t.Embed_Images
		cp.LexiconTypeID = "com.example.embed#images"
		return json.Marshal(&cp)
	}
	if t.Raw != nil {
		if t.Raw.Encoding != "json" {
			return nil, fmt.Errorf("cannot marshal raw %s record as JSON in union Embed_Extras_Elem", t.Raw.Encoding)
		}
		return t.Raw.Bytes, nil
	}
	return nil, fmt.Errorf("cannot marshal empty union Embed_Extras_Elem as JSON")
}

func (t *Embed_Extras_Elem) UnmarshalJSON(b []byte) error {
	typ, err := glex.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "com.example.embed#external":
		t.Embed_External = new(Embed_External)
		return json.Unmarshal(b, t.Embed_External)
	case "com.example.embed#images":
		t.Embed_Images = new(Embed_Images)
		return json.Unmarshal(b, t.Embed_Images)
	default:
		t.Raw = &glex.RawRecord{Type: typ, Encoding: "json", Bytes: append([]byte(nil), b...)}
		return nil
	}
}

// MarshalCBOR implements drisl.Marshaler, emitting the set variant (stamped
// with its $type) per the atproto union wire format. go-dasl invokes this
// when the union appears inside another record, so nested unions serialize
// correctly.
func (t Embed_Extras_Elem) MarshalCBOR() ([]byte, error) {
	if t.Embed_External != nil {
		cp := *t.Embed_External
		cp.LexiconTypeID = "com.example.embed#external"
		return glex.MarshalCBORBytes(&cp)
	}
	if t.Embed_Images != nil {
		cp := *t.Embed_Images
		cp.LexiconTypeID = "com.example.embed#images"
		return glex.MarshalCBORBytes(&cp)
	}
	if t.Raw != nil {
		if t.Raw.Encoding != "cbor" {
			return nil, fmt.Errorf("cannot marshal raw %s record as CBOR in union Embed_Extras_Elem", t.Raw.Encoding)
		}
		return t.Raw.Bytes, nil
	}
	return nil, fmt.Errorf("cannot marshal empty union Embed_Extras_Elem as CBOR")
}

func (t *Embed_Extras_Elem) UnmarshalCBOR(b []byte) error {
	typ, err := glex.CborTypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "com.example.embed#external":
		t.Embed_External = new(Embed_External)
		return glex.UnmarshalCBORBytes(b, t.Embed_External)
	case "com.example.embed#images":
		t.Embed_Images = new(Embed_Images)
		return glex.UnmarshalCBORBytes(b, t.Embed_Images)
	default:
		t.Raw = &glex.RawRecord{Type: typ, Encoding: "cbor", Bytes: append([]byte(nil), b...)}
		return nil
	}
}

// Optional fallback media.
type Embed_Fallback struct {
	Embed_External *Embed_External
	Embed_Images   *Embed_Images
	// Raw preserves a variant whose $type is not in this union's generated
	// set, so unrecognized variants still round-trip losslessly through
	// decode/re-encode. Nil when a known variant is set.
	Raw *glex.RawRecord
}

// MarshalJSON emits the set variant, stamped with its $type, per the atproto
// union wire format. The value receiver stamps a copy, so the variant is
// never mutated and both Embed_Fallback and *Embed_Fallback marshal correctly.
func (t Embed_Fallback) MarshalJSON() ([]byte, error) {
	if t.Embed_External != nil {
		cp := *t.Embed_External
		cp.LexiconTypeID = "com.example.embed#external"
		return json.Marshal(&cp)
	}
	if t.Embed_Images != nil {
		cp := *t.Embed_Images
		cp.LexiconTypeID = "com.example.embed#images"
		return json.Marshal(&cp)
	}
	if t.Raw != nil {
		if t.Raw.Encoding != "json" {
			return nil, fmt.Errorf("cannot marshal raw %s record as JSON in union Embed_Fallback", t.Raw.Encoding)
		}
		return t.Raw.Bytes, nil
	}
	return nil, fmt.Errorf("cannot marshal empty union Embed_Fallback as JSON")
}

func (t *Embed_Fallback) UnmarshalJSON(b []byte) error {
	typ, err := glex.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "com.example.embed#external":
		t.Embed_External = new(Embed_External)
		return json.Unmarshal(b, t.Embed_External)
	case "com.example.embed#images":
		t.Embed_Images = new(Embed_Images)
		return json.Unmarshal(b, t.Embed_Images)
	default:
		t.Raw = &glex.RawRecord{Type: typ, Encoding: "json", Bytes: append([]byte(nil), b...)}
		return nil
	}
}

// MarshalCBOR implements drisl.Marshaler, emitting the set variant (stamped
// with its $type) per the atproto union wire format. go-dasl invokes this
// when the union appears inside another record, so nested unions serialize
// correctly.
func (t Embed_Fallback) MarshalCBOR() ([]byte, error) {
	if t.Embed_External != nil {
		cp := *t.Embed_External
		cp.LexiconTypeID = "com.example.embed#external"
		return glex.MarshalCBORBytes(&cp)
	}
	if t.Embed_Images != nil {
		cp := *t.Embed_Images
		cp.LexiconTypeID = "com.example.embed#images"
		return glex.MarshalCBORBytes(&cp)
	}
	if t.Raw != nil {
		if t.Raw.Encoding != "cbor" {
			return nil, fmt.Errorf("cannot marshal raw %s record as CBOR in union Embed_Fallback", t.Raw.Encoding)
		}
		return t.Raw.Bytes, nil
	}
	return nil, fmt.Errorf("cannot marshal empty union Embed_Fallback as CBOR")
}

func (t *Embed_Fallback) UnmarshalCBOR(b []byte) error {
	typ, err := glex.CborTypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "com.example.embed#external":
		t.Embed_External = new(Embed_External)
		return glex.UnmarshalCBORBytes(b, t.Embed_External)
	case "com.example.embed#images":
		t.Embed_Images = new(Embed_Images)
		return glex.UnmarshalCBORBytes(b, t.Embed_Images)
	default:
		t.Raw = &glex.RawRecord{Type: typ, Encoding: "cbor", Bytes: append([]byte(nil), b...)}
		return nil
	}
}

// The primary embedded media.
type Embed_Media struct {
	Embed_External *Embed_External
	Embed_Images   *Embed_Images
	// Raw preserves a variant whose $type is not in this union's generated
	// set, so unrecognized variants still round-trip losslessly through
	// decode/re-encode. Nil when a known variant is set.
	Raw *glex.RawRecord
}

// MarshalJSON emits the set variant, stamped with its $type, per the atproto
// union wire format. The value receiver stamps a copy, so the variant is
// never mutated and both Embed_Media and *Embed_Media marshal correctly.
func (t Embed_Media) MarshalJSON() ([]byte, error) {
	if t.Embed_External != nil {
		cp := *t.Embed_External
		cp.LexiconTypeID = "com.example.embed#external"
		return json.Marshal(&cp)
	}
	if t.Embed_Images != nil {
		cp := *t.Embed_Images
		cp.LexiconTypeID = "com.example.embed#images"
		return json.Marshal(&cp)
	}
	if t.Raw != nil {
		if t.Raw.Encoding != "json" {
			return nil, fmt.Errorf("cannot marshal raw %s record as JSON in union Embed_Media", t.Raw.Encoding)
		}
		return t.Raw.Bytes, nil
	}
	return nil, fmt.Errorf("cannot marshal empty union Embed_Media as JSON")
}

func (t *Embed_Media) UnmarshalJSON(b []byte) error {
	typ, err := glex.TypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "com.example.embed#external":
		t.Embed_External = new(Embed_External)
		return json.Unmarshal(b, t.Embed_External)
	case "com.example.embed#images":
		t.Embed_Images = new(Embed_Images)
		return json.Unmarshal(b, t.Embed_Images)
	default:
		t.Raw = &glex.RawRecord{Type: typ, Encoding: "json", Bytes: append([]byte(nil), b...)}
		return nil
	}
}

// MarshalCBOR implements drisl.Marshaler, emitting the set variant (stamped
// with its $type) per the atproto union wire format. go-dasl invokes this
// when the union appears inside another record, so nested unions serialize
// correctly.
func (t Embed_Media) MarshalCBOR() ([]byte, error) {
	if t.Embed_External != nil {
		cp := *t.Embed_External
		cp.LexiconTypeID = "com.example.embed#external"
		return glex.MarshalCBORBytes(&cp)
	}
	if t.Embed_Images != nil {
		cp := *t.Embed_Images
		cp.LexiconTypeID = "com.example.embed#images"
		return glex.MarshalCBORBytes(&cp)
	}
	if t.Raw != nil {
		if t.Raw.Encoding != "cbor" {
			return nil, fmt.Errorf("cannot marshal raw %s record as CBOR in union Embed_Media", t.Raw.Encoding)
		}
		return t.Raw.Bytes, nil
	}
	return nil, fmt.Errorf("cannot marshal empty union Embed_Media as CBOR")
}

func (t *Embed_Media) UnmarshalCBOR(b []byte) error {
	typ, err := glex.CborTypeExtract(b)
	if err != nil {
		return err
	}

	switch typ {
	case "com.example.embed#external":
		t.Embed_External = new(Embed_External)
		return glex.UnmarshalCBORBytes(b, t.Embed_External)
	case "com.example.embed#images":
		t.Embed_Images = new(Embed_Images)
		return glex.UnmarshalCBORBytes(b, t.Embed_Images)
	default:
		t.Raw = &glex.RawRecord{Type: typ, Encoding: "cbor", Bytes: append([]byte(nil), b...)}
		return nil
	}
}

// Embed_External is a "external" in the com.example.embed schema.
//
// An external link embed.
type Embed_External struct {
	LexiconTypeID string `json:"$type,omitempty"`
	// uri: The external URI.
	Uri string `json:"uri"`
}

// RecordTypeID implements glex.Record.
func (t *Embed_External) RecordTypeID() string { return "com.example.embed#external" }

func (t *Embed_External) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	// stamp $type on a copy so marshal never mutates the record
	cp := *t
	cp.LexiconTypeID = "com.example.embed#external"
	return glex.MarshalCBOR(w, &cp)
}

func (t *Embed_External) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}

// Embed_Images is a "images" in the com.example.embed schema.
//
// An image embed.
type Embed_Images struct {
	LexiconTypeID string `json:"$type,omitempty"`
	// alt: Alt text.
	Alt string `json:"alt"`
}

// RecordTypeID implements glex.Record.
func (t *Embed_Images) RecordTypeID() string { return "com.example.embed#images" }

func (t *Embed_Images) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	// stamp $type on a copy so marshal never mutates the record
	cp := *t
	cp.LexiconTypeID = "com.example.embed#images"
	return glex.MarshalCBOR(w, &cp)
}

func (t *Embed_Images) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}
