// Code generated by glex; DO NOT EDIT.

// Lexicon schema: com.example.interactionView

package comexample

import (
	"encoding/json"
	"io"

	glex "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
)

func init() {
	glex.RegisterType("com.example.interactionView#main", &InteractionView{})
}

// Input/output view shape for interactions.
type InteractionView struct {
	LexiconTypeID string `json:"$type,omitempty"`
	// count: Interaction count.
	Count *int64 `json:"count,omitempty"`
	// subject: The post being interacted with.
	Subject Post `json:"subject"`
}

// RecordTypeID implements glex.Record.
func (t *InteractionView) RecordTypeID() string { return "com.example.interactionView" }

// MarshalJSON stamps the $type field, like MarshalCBOR does. The value
// receiver operates on a copy, so the record is never mutated and both
// InteractionView and *InteractionView marshal with $type.
func (t InteractionView) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "com.example.interactionView"
	type alias InteractionView
	return json.Marshal((alias)(t))
}

func (t *InteractionView) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	// stamp $type on a copy so marshal never mutates the record
	cp := *t
	cp.LexiconTypeID = "com.example.interactionView"
	return glex.MarshalCBOR(w, &cp)
}

func (t *InteractionView) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}
