// Code generated by glex; DO NOT EDIT.

// Lexicon schema: com.example.createLike

package comexample

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
	"io"
)

type CreateLike_Input struct {
	LexiconTypeID string `json:"$type"`
	// note: Optional note.
	Note *string `json:"note,omitempty"`
	// uri: The post URI to like.
	Uri string `json:"uri"`
}

func (t *CreateLike_Input) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "com.example.createLike#main"
	return glexrt.MarshalCBOR(w, t)
}

func (t *CreateLike_Input) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}

// CreateLike calls the XRPC method "com.example.createLike".
//
// Create a like on a post.
func CreateLike(ctx context.Context, c glexrt.LexClient, input *CreateLike_Input) (*InteractionView, error) {
	var out InteractionView

	if err := c.LexDo(ctx, glexrt.Procedure, "application/json", "com.example.createLike", nil, input, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
