// Code generated by glex; DO NOT EDIT.

// Lexicon schema: com.example.getInteractions

package comexample

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	glex "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
	"io"
)

// GetInteractions calls the XRPC method "com.example.getInteractions".
//
// Get the interaction count for a post.
//
// limit: Optional limit.
// uri: The post URI.
func GetInteractions(ctx context.Context, c glex.LexClient, limit *int64, uri string) (*InteractionView, error) {
	var out InteractionView

	params := map[string]interface{}{}
	if limit != nil {
		params["limit"] = *limit
	}
	params["uri"] = uri

	if err := c.LexDo(ctx, glex.Query, "", "com.example.getInteractions", params, nil, &out); err != nil {
		return nil, err
	}
	return &out, nil
}
