// Code generated by glex; DO NOT EDIT.

// Lexicon schema: com.example.interactionView

package comexample

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
	"io"
)

func init() {
	glexrt.RegisterType("com.example.interactionView#main", &InteractionView{})
}

// Input/output view shape for interactions.
type InteractionView struct {
	LexiconTypeID string `json:"$type"`
	// count: Interaction count.
	Count *int64 `json:"count,omitempty"`
	// subject: The post being interacted with.
	Subject Post `json:"subject"`
}

func (t *InteractionView) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "com.example.interactionView"
	return glexrt.MarshalCBOR(w, t)
}

func (t *InteractionView) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}
