// Code generated by glex; DO NOT EDIT.

// Lexicon schema: com.example.post

package comexample

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	glexrt "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
	"io"
)

func init() {
	glexrt.RegisterType("com.example.post", &Post{})
}

// A test record.
type Post struct {
	LexiconTypeID string `json:"$type"`
	// createdAt: Creation timestamp.
	CreatedAt string `json:"createdAt"`
	// image: An optional image attachment.
	Image *glexrt.Blob `json:"image,omitempty"`
	// rawData: Optional raw binary data.
	RawData glexrt.Bytes `json:"rawData,omitempty"`
	// replyTo: A link to another post.
	ReplyTo *Post `json:"replyTo,omitempty"`
	// tags: Optional tags.
	Tags []string `json:"tags,omitempty"`
	// text: The body text of the post.
	Text string `json:"text"`
}

func (t *Post) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	t.LexiconTypeID = "com.example.post"
	return glexrt.MarshalCBOR(w, t)
}

func (t *Post) UnmarshalCBOR(r io.Reader) error {
	return glexrt.UnmarshalCBOR(r, t)
}
