// Code generated by glex; DO NOT EDIT.

// Lexicon schema: com.example.post

package comexample

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	glex "github.com/streamplace/glex/runtime"
	cbg "github.com/whyrusleeping/cbor-gen"
	"io"
)

func init() {
	glex.RegisterType("com.example.post", &Post{})
}

// A test record.
type Post struct {
	LexiconTypeID string `json:"$type,omitempty"`
	// createdAt: Creation timestamp.
	CreatedAt string `json:"createdAt"`
	// image: An optional image attachment.
	Image *glex.Blob `json:"image,omitempty"`
	// rawData: Optional raw binary data.
	RawData glex.Bytes `json:"rawData,omitempty"`
	// replyTo: A link to another post.
	ReplyTo *Post `json:"replyTo,omitempty"`
	// tags: Optional tags.
	Tags []string `json:"tags,omitempty"`
	// text: The body text of the post.
	Text string `json:"text"`
}

// RecordTypeID implements glex.Record.
func (t *Post) RecordTypeID() string { return "com.example.post" }

// MarshalJSON stamps the $type field, like MarshalCBOR does. The value
// receiver operates on a copy, so the record is never mutated and both
// Post and *Post marshal with $type.
func (t Post) MarshalJSON() ([]byte, error) {
	t.LexiconTypeID = "com.example.post"
	type alias Post
	return json.Marshal((alias)(t))
}

func (t *Post) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}
	// stamp $type on a copy so marshal never mutates the record
	cp := *t
	cp.LexiconTypeID = "com.example.post"
	return glex.MarshalCBOR(w, &cp)
}

func (t *Post) UnmarshalCBOR(r io.Reader) error {
	return glex.UnmarshalCBOR(r, t)
}
